name: "Bug report"
description: "Create a report to help us improve"
title: "[bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Problem description
      description: |
        A clear and concise description of what the problem is. You may attach debug logs, screenshots, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: textarea
    attributes:
      label: System information
      description: Information about your operating system.
      value: |
        OS: ...
        Arch: ...
        Node.js: v...
        Fuwa: v...
    validations:
      required: true
